version: "3.4"

networks:
  backend:

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  picspy-godbox:
    image: tcatonet/godbox
    privileged: true
    ports:
      - 8081:8080
    environment: 
      API_MAX_PAYLOAD_SIZE: 327680
    networks: 
      - backend

    