FROM tcatonet/testgodbox

#CMD adduser -D root
#USER root
#RUN chmod 666 /var/run/docker.sock
#CMD groupadd docker
#CMD sudo chmod 666 -R /var
#CMD find / -name main.rs
#CMD grep -r 'PORT' -l --null . | xargs -0 sed -i 's#PORT#$PORT#g'
#CMD /bin/sh -c godbox