FROM tcatonet/api_picspy-godbox

CMD adduser -D root
USER root
#RUN chmod 666 /var/run/docker.sock
#CMD groupadd docker
CMD sudo chmod 666 -R /var
# && find / -name docker.sock


#CMD /bin/sh -c godbox