name: build-and-push

on:
  release:
    types: [created]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code
        


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/vagahbond/picspy/godbox
            ${{ secrets.DOCKER_REGISTRY }}/vagahbond/picspy/godbox:${{ steps.tag_name.outputs.TAG_NAME }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: Deploy Stage
      #   uses: fjogeleit/http-request-action@master
      #   with:
      #     url: ${{ secrets.PROD_WEBHOOK }}
      #     method: 'POST'
        